### ISSUE TITLE
Error when no groups are defined

### ISSUE THREAD

**Issue by sofagris** [tomplayford/aiohelvar#4]
When connecting to the 920 router, I'm receiving some errors due to no groups defined on the router:
Testing result as below before adding it to a array seems to resolve the issue (At least as a quick fix).

File: groups.py

```
    if response.result is not None:
        groups = [Group(group_id) for group_id in response.result.split(",")]

        for group in groups:
            router.groups.register_group(group)
            asyncio.create_task(update_name(router, group.group_id))
            asyncio.create_task(update_group_devices(router, group.group_id))
            asyncio.create_task(update_group_last_scene(router, group.group_id))
```

Example: 

Connecting to router at address: 10.47.14.20...
Connected to router on workgroup: New Router.
Initializing router...
Traceback (most recent call last):
  File "c:\users\roy\Desktop\Helvar Test.py", line 63, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "c:\users\roy\Desktop\Helvar Test.py", line 30, in main
    await router.initialize()
  File "C:\Users\microy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohelvar\router.py", line 198, in initialize
    await self.get_groups()
  File "C:\Users\roy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohelvar\router.py", line 214, in get_groups
    await get_groups(self)
  File "C:\Users\roy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohelvar\groups.py", line 189, in get_groups
    groups = [Group(group_id) for group_id in response.result.split(",")]
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002503ED2B1F0>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 751, in call_soon
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

**Comment by tomplayford** [comment]
Well found @sofagris - should be fixed now.
