### ISSUE TITLE
It would appear I have an error retrieving devices 

### ISSUE THREAD

**Issue by 7sorium** [tomplayford/aiohelvar#6]
```

Connecting to router at address: 192.168.1.2...
Connected to router on workgroup: New Router.
Initializing router...
Request command >V:2,C:100,@0.1.1# triggered an error back from the router: !V:2,C:100,@0.1.1=9#.
Request command >V:2,C:100,@0.1.2# triggered an error back from the router: !V:2,C:100,@0.1.2=9#.
Request command >V:2,C:100,@0.1.3# triggered an error back from the router: !V:2,C:100,@0.1.3=9#.
Request command >V:2,C:100,@0.1.4# triggered an error back from the router: !V:2,C:100,@0.1.4=9#.
Router devices: 
Router groups: 
    Group 1: Garaza. Has 0 devices.
    Group 2: Led Box. Has 0 devices.
    Group 3: Strop Zapad. Has 0 devices.
    Group 4: Strop Istok. Has 0 devices.
    Group 5: Strop Sve. Has 0 devices.
    Group 6: Group Test. Has 0 devices.
    Group 7: Bg. Has 0 devices.
    Group 8: Rolo. Has 0 devices.
    Group 9: Kotlovnica. Has 0 devices.
    Group 10: Rolete. Has 0 devices.
    Group 11: Rolete Garaza. Has 0 devices.
    Group 12: Vanjska. Has 0 devices.
    Group 13: Rolete toalet. Has 0 devices.
    Group 14: Vanjska Ispred. Has 0 devices.
    Group 15: Pumpa. Has 0 devices.
    Group 16: Bg Only. Has 0 devices.
Router scenes: 
    @1.1.1: None
    @1.1.2: None
    @1.1.3: None
    @1.1.4: None
    @1.1.5: None
    @1.1.6: None
    @1.1.7: None

... mostly None here, a few connect to a scene...

    @16.8.14: None
    @16.8.15: None
    @16.8.16: None
Traceback (most recent call last):
  File "simple_example.py", line 63, in <module>
    asyncio.run(main())
  File "/Users/mark/.pyenv/versions/3.7.12/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/mark/.pyenv/versions/3.7.12/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "simple_example.py", line 48, in main
    device_to_flash = list(router.devices.devices.values())[0]
IndexError: list index out of range

```

All of these groups have devices, 1 to 8 or more. Any suggestions?

**Comment by sofagris** [comment]
It looks for me like you have wrong cluster and router id. 

The cluster id equals ip subnet. (192.168.**1**.2), and the router id equals host ip (192.168.1.**2**).

If You do like this in the simple_example.py, you will get the correct result.

router_ip_address = "10.47.14.20"
router_helvarnet_port = 50000
    
cluster_id = router_ip_address.split(".")[2]
router_id = router_ip_address.split(".")[3]
print(f"Cluster ID = {cluster_id}, Router ID = {router_id}")

device_address_to_flash = HelvarAddress(cluster_id, router_id, 2, 1) # <-- Remember to change DALI bus id and device id.

# set up some verbose logging.
console = logging.StreamHandler()
console.setLevel(logging.INFO)
logging.getLogger().addHandler(console)

# Connect to router. Router object will keep the connection alive.
print(f"Connecting to router at address: {router_ip_address}...")
router = Router(router_ip_address, router_helvarnet_port, cluster_id, router_id) 
await router.connect()

**Comment by 7sorium** [comment]
Thanks for the instructions... but sorry, it would appear I'm still retarded...

My Dali router real IP's 10.1.1.2 (I changed in the original report to 192.168.1.2... just because well...)
Dali Subnet: 10.1.1.2.1
ID (right below address in the Win app): 65795
Cluster ID: 10.1.1.0
Cluster Member ID: 0.0.0.2
Cluster Comms Port: 60005 (I tried changing that as well from 5000)
Router ID: 166026

I tried a couple of combinations, including your cluster/router suggestion but no dice, always the same error. I'm guessing it's right in front of me :( And yes I used your snippet in the simple_example to extract the cluster/router id.

**Comment by sofagris** [comment]
If your Helvar Router's IP is 10.1.1.2, your DALI Cluster ID will be 1, and your Router ID will be 2 as shown in the documentation for  [version 4.2.18](http://www.lightmoves.com.au/downloads/Documentation/Helvar/Designer_Complete_4_2_18_HelpFile.pdf) PDF page 42.
The Cluster ID and Router ID information provided by the Designer is just confusing. 

Acording to the documentation, the port 50000 is for HelvarNet TCP: 
"To establish a TCP connection and therefore communicate with the router, the third-party device is required to connect to listener port number 50000."

**Comment by 7sorium** [comment]
That got me further along, thanks, still though:


```
Initializing router...
Request command >V:2,C:100,@1.2.2# triggered an error back from the router: !V:2,C:100,@1.2.2=11#.
Request command >V:2,C:100,@1.2.3# triggered an error back from the router: !V:2,C:100,@1.2.3=11#.
Request command >V:2,C:100,@1.2.4# triggered an error back from the router: !V:2,C:100,@1.2.4=11#.
Router devices: 
    All devices detected fine here...
```

And finally after scanning a bunch of stuff again:

```
Couldn't find device with address: @1.2.2.1
Task exception was never retrieved
future: <Task finished coro=<Devices.set_device_load_level.<locals>.task() done, defined at /Users/mark/src/aiohelvar/aiohelvar/devices.py:260> exception=KeyError(<aiohelvar.parser.address.HelvarAddress object at 0x10f1091d0>)>
Traceback (most recent call last):
  File "/Users/mark/src/aiohelvar/aiohelvar/devices.py", line 274, in task
    await devices.update_device_load_level(address, load_level)
  File "/Users/mark/src/aiohelvar/aiohelvar/devices.py", line 208, in update_device_load_level
    await self._update_device_param(address, "load_level", float(load_level))
  File "/Users/mark/src/aiohelvar/aiohelvar/devices.py", line 232, in _update_device_param
    setattr(self.devices[address], param, value)
KeyError: <aiohelvar.parser.address.HelvarAddress object at 0x10f1091d0>
Couldn't find device with address: @1.2.2.1
Task exception was never retrieved
future: <Task finished coro=<Devices.set_device_load_level.<locals>.task() done, defined at /Users/mark/src/aiohelvar/aiohelvar/devices.py:260> exception=KeyError(<aiohelvar.parser.address.HelvarAddress object at 0x10f1091d0>)>
Traceback (most recent call last):
  File "/Users/mark/src/aiohelvar/aiohelvar/devices.py", line 274, in task
    await devices.update_device_load_level(address, load_level)
  File "/Users/mark/src/aiohelvar/aiohelvar/devices.py", line 208, in update_device_load_level
    await self._update_device_param(address, "load_level", float(load_level))
  File "/Users/mark/src/aiohelvar/aiohelvar/devices.py", line 232, in _update_device_param
    setattr(self.devices[address], param, value)
KeyError: <aiohelvar.parser.address.HelvarAddress object at 0x10f1091d0>
```


I'll try in the following days when I catch some time if I can control them. My end goal is to make an interface into iobroker since I got everything else hooked up with it.

**Comment by tomplayford** [comment]
@7sorium - are you trying to connect to a cluster with more than one router? 

If so - that's not something I've been able to test (I don't have access to one).

**Comment by omega** [comment]
Just stumbled upon this issue while testing this, would it make sense for the default `cluster_id` and `router_id` to be picked up from the `host`, if the `host` is an IP? if they are always taken from there anyway?

**Comment by tomplayford** [comment]
and now in https://github.com/tomplayford/homeassistant_helvar/releases/tag/0.2.1
