### ISSUE TITLE
Error while connecting to Helvar router 910

### ISSUE THREAD

**Issue by gardart** [tomplayford/aiohelvar#7]
Hi, thank you for putting this together. I was trying out your code with my Helvar 910 router. Im getting this error below.
Any ideas? 

Connecting to router at address: 192.168.1.20...
Connected to router on workgroup: x.
Initializing router...
Request command >V:2,C:100,@1.20.3# triggered an error back from the router: !V:2,C:100,@1.20.3=11#.
Request command >V:2,C:100,@1.20.4# triggered an error back from the router: !V:2,C:100,@1.20.4=11#.
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/x/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/x/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/x/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/x/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/x/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/x/.vscode/extensions/ms-python.python-2023.8.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/x/code/helvar-prufa/test.py", line 44, in <module>
    asyncio.run(main())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/x/code/helvar-prufa/test.py", line 30, in main
    await router.initialize()
  File "/Users/x/.local/share/virtualenvs/helvar-prufa-qfz8EuSG/lib/python3.8/site-packages/aiohelvar/router.py", line 207, in initialize
    await self.get_scenes()
  File "/Users/x/.local/share/virtualenvs/helvar-prufa-qfz8EuSG/lib/python3.8/site-packages/aiohelvar/router.py", line 222, in get_scenes
    await get_scenes(self, self.groups)
  File "/Users/x/.local/share/virtualenvs/helvar-prufa-qfz8EuSG/lib/python3.8/site-packages/aiohelvar/scenes.py", line 74, in get_scenes
    parts = response.result.strip("@").split("@")
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by theclockmaster** [comment]
Hi Gardart, not sure if you managed to solve this.

Looking at the HelvarNET documentation, it seems that the reply 11 is on the address which indicates that the device at that IP address does not exist.

![image](https://github.com/tomplayford/aiohelvar/assets/12816113/58b9cdc7-f836-455d-8b28-31b37a50c439)
